### ISSUE TITLE
-u 3 option for using unmapped character as the replacement character (self-replacement)

### ISSUE THREAD

**Issue by kaanchan** [silnrsi/teckit#18]
After investing a fair bit of time (and not reading all documentation first), I came to realize txtconv won't simply ignore characters with no mapping specified. Hence if my source doc is an **unstructured** mix of Unicode and legacy text, all of the Unicode text gets replaced with the default/specified replacement character.

Since txtconv has to replace characters missing a mapping with the replacement character anyways, is there any reason not to allow replacing the unmapped character with itself? I understand that txtconv seeks to guarantee the final output is uniformly of the designated encoding, but giving an option to bypass this constraint would make the tool even more flexible (and useful for many unstructured, mixed encoding scenarios).

adding a "-u 3" option could be a way to implement this. If specified as an option to txtconv, then txtconv ignores or replaces unmapped characters with that same character. A warning could be printed if the self-replaced character(s) does not match the desired final encoding.

**Comment by devosb** [comment]
IIRC, `txtconv` will ignore characters in
- byte to byte
- Unicode to Unicode

passes. So it is only in byte to Unicode passes that your change would apply to.

For unstructured text, how do you expect `txtconv` know what bytes are part of a Unicode character, and what bytes are legacy text? It is possible that a byte representing a legacy character will be used as part of a multi byte sequence that represents a Unicode character. So I am confused what should be done with a byte that could be used in either a legacy or Unicode context. Do you have an example of unstructured that your are trying to process? Since this text field is storing Unicode you could specify the hexadecimal value of the bytes in your file.

I suspect that allowing an unmapped byte to be present in the Unicode output would be a bit of work. IIRC, when converting to Unicode, everything is stored at UTF-32BE. So when the conversion from UTF-32BE is made to UTF-8 or UTF-16LE, a table would have to be constructed to remember the value of that unmapped byte, and output that byte.

TECkit does come with a tool called `sfconv` that can convert a file with mixed legacy and Unicode text to Unicode. But the tool requires markup to separate the legacy bytes from Unicode. The goal is to move away from files with mixed encoding, which is why such an option as your propose does not exist.

**Comment by kaanchan** [comment]
Thanks for the reply with detailed explanation. I am unfamiliar with the term _IIRC_ and the [various Unicode encodings](https://en.wikipedia.org/wiki/Comparison_of_Unicode_encodings), the latter of which I was able to Google and get some background on. What is IIRC?

> So it is only in byte to Unicode passes that your change would apply to.

Correct. That is the pass type I am working on; but wanted to allow for byte/Unicode -> Unicode. In the process of trying to switch an organization to Unicode encoded Devanagari, the document pool has Unicode encoded Devanagari mixed in with legacy encoded Devanagari due to a legacy IME being used at same time as Unicode IME (not all users adopt new tools at the same rate or level of acceptance). The Unicode font we found as a close replacement is close enough that is visually similar and hard to distinguish visually, when mixed.

> यच्च किंचिज्जगत्सर्वं दृश्यते श्रूयतेऽथवा
> ‚ã¶¦ãºãÃãäÖÍÞã ¦ã¦ÔãÌãÄ Ì¾ãã¹¾ã ¶ããÀã¾ã¥ã: ãäÔ©ã¦ã:

![image](https://user-images.githubusercontent.com/13602253/49093139-7f996200-f289-11e8-966c-9cf777111847.png)

The goal now is to find a tool for converting everything to 100% Unicode Devangari in one go. The non-tech users will use a simple web interface for copy-pasting text needing to be converted. Mixed encodings in; Unicode only out. Once everything is converted to Unicode, we would drop the IME which allows legacy encoded Devanagari.

> For unstructured text, how do you expect `txtconv` know what bytes are part of a Unicode character, and what bytes are legacy text?

I have no idea. I was thinking of it very high-level, totally unaware of the underlying technical details and considerations. In my ignorance and based on the code found in Engine.cpp, I thought by the time the replacement character logic was applied, all the low-level stuff was taken care of.

line 1166:
```
case kRepElem_Unmapped:
     if (bOutputIsUnicode == bInputIsUnicode) {
          outputChar(inChar);
```

and lines 1175-1186:
```
switch (converter->unmappedBehavior) {
     case kOptionsUnmapped_DontUseReplacementChar:
          return kUnmappedChar;

     case kOptionsUnmapped_UseReplacementCharWithWarning:
          converter->warningStatus |= kStatus_UsedReplacement;
          // fall through
 
     default:	// case kOptionsUnmapped_UseReplacementCharSilently:
          outputChar(READ(tableHeader->replacementChar));
          break;
}
```

Hence, I thought it might be possible to add something like below after first `case` statement in the `switch` above:
```
case kOptionsUnmapped_UseUnmappedCharWithWarning:
          converter->warningStatus |= kStatus_UsedUnmappedChar;
          outputChar(inChar);
          break;
```

> Since this text field is storing Unicode you could specify the hexadecimal value of the bytes in your file.

I need to keep this simple for non-tech users to be able to use. The very proposal of converting and inputting everything in Unicode has taken over 4 years. These documents are working papers and books which will be on the web. As soon as we convert them to Unicode, they can be searched, indexed, analyzed, ...

>TECkit does come with a tool called sfconv that can convert a file with mixed legacy and Unicode text to Unicode. 

Yes, I may have to try that if I cannot find another solution. 

>The goal is to move away from files with mixed encoding, which is why such an option as your propose does not exist.

I agree completely! Which is why I am looking for an option such as the one I proposed. We want to go from mixed encoding to pure Unicode encoding, and never go back to mixed. Until I can found a way to convert in mass, users will continue using the legacy tools which input the Devanagari in legacy encoding.

**Comment by devosb** [comment]
On 2018-11-27 9:15 a.m., kaanchan wrote:

> Thanks for the reply with detailed explanation. I am unfamiliar with
> the term /IIRC/ and the various Unicode encodings
> <https://en.wikipedia.org/wiki/Comparison_of_Unicode_encodings>, the
> latter of which I was able to Google and get some background on. What
> is IIRC?
>
Sorry that I was not clear. IIRC, in this case, means If I Remember
Correctly. What I meant was I think what I am writing is correct, but my
memory maybe off. That is, I am writing from something I understood a
while ago, and have not checked recently with the documentation, source
code, nor experimentation.

One of the links on the page above goes to
https://en.wikipedia.org/wiki/UTF-8 It talks about handling legacy bytes
and UTF-8 bytes, and might apply to your situation.

>     So it is only in byte to Unicode passes that your change would
>     apply to.
>
> Correct. That is the pass type I am working on; but wanted to allow
> for byte/Unicode -> Unicode. In the process of trying to switch an
> organization to Unicode encoded Devanagari, the document pool has
> Unicode encoded Devanagari mixed in with legacy encoded Devanagari due
> to a legacy IME being used at same time as Unicode IME (not all users
> adopt new tools at the same rate or level of acceptance). The Unicode
> font we found as a close replacement is close enough that is visually
> similar and hard to distinguish visually, when mixed.
>
>     यच्च किंचिज्जगत्सर्वं दृश्यते श्रूयतेऽथवा
>     ‚ã¶¦ãºãÃãäÖÍÞã ¦ã¦ÔãÌãÄ Ì¾ãã¹¾ã ¶ããÀã¾ã¥ã: ãäÔ©ã¦ã:
>
I noticed you used the Kokila font, which is provided with Windows, so I
assume you are using Windows. If not, let me know. TECkit does not know
or care about what font is used, it just converts the bytes representing
characters. What application did you copy and paste the above example from?

> image
> <https://user-images.githubusercontent.com/13602253/49093139-7f996200-f289-11e8-966c-9cf777111847.png>
>
> The goal now is to find a tool for converting everything to 100%
> Unicode Devangari in one go. The non-tech users will use a simple web
> interface for copy-pasting text needing to be converted. Mixed
> encodings in; Unicode only out. Once everything is converted to
> Unicode, we would drop the IME which allows legacy encoded Devanagari.
>
I suspect that when you copy and paste the text into a website, ALL the
text will be "Unicode". Some of the text will be Unicode Devanagari,
some of the text will be hacked Unicode (so a legacy encoding, but run
through codepage 1252 (I assume you have a Western version of Windows)
to convert the data from bytes to hacked Unicode). Hacked Unicode being
the application stores text in something like UTF-16, but the data has
not been actually mapped to Unicode characters, just "wide" characters.

So to convert to Unicode Devanagari text, the legacy data will have to
be converted back to bytes before being used with txtconv.

>     For unstructured text, how do you expect |txtconv| know what bytes
>     are part of a Unicode character, and what bytes are legacy text?
>
> I have no idea. I was thinking of it very high-level, totally unaware
> of the underlying technical details and considerations. In my
> ignorance and based on the code found in Engine.cpp, I thought by the
> time the replacement character logic was applied, all the low-level
> stuff was taken care of.
>
> line 1166:
>
> |case kRepElem_Unmapped: if (bOutputIsUnicode == bInputIsUnicode) {
> outputChar(inChar);|

I think this would only apply to Unicode to Unicode (and maybe byte to
byte) passes as well.

||

> and lines 1175-1186:
>
> |switch (converter->unmappedBehavior) { case
> kOptionsUnmapped_DontUseReplacementChar: return kUnmappedChar; case
> kOptionsUnmapped_UseReplacementCharWithWarning:
> converter->warningStatus |= kStatus_UsedReplacement; // fall through
> default: // case kOptionsUnmapped_UseReplacementCharSilently:
> outputChar(READ(tableHeader->replacementChar)); break; } |
>
> Hence, I thought it might be possible to add something like below
> after first |case| statement in the |switch| above:
>
> |case kOptionsUnmapped_UseUnmappedCharWithWarning:
> converter->warningStatus |= kStatus_UsedUnmappedChar;
> outputChar(inChar); break;|

I think this will break when the output buffer (in UTF-32BE I suspect)
is converted to the desired Unicode format (such as UTF-8, UTF-16LE,
etc.) as process will expect a buffer of 32 bit codepoints, not 32 bit
codepoints mixed in with a 8 bit values.||

>     Since this text field is storing Unicode you could specify the
>     hexadecimal value of the bytes in your file.
>
Ah, sorry. By text field I meant a GitHub text field, where this
conversation is happening. (Although, I am writing this text in my email
client, so we will see how GitHub handles it.) I copied your mixed
encoding example to a text editor, then saved the text as UTF-8.

One of the bytes in 0x87. This occurs in the Devanagari text as the
UTF-8 encoding of U+0947 DEVANAGARI VOWEL SIGN E. This vowel sign is
stored as the UTF-8 bytes 0xE0 0xA5 0x87. However, in codepage 1252,
byte 0x87 is DOUBLE DAGGER, and DOUBLE DAGGER looks like it is used in
the APS encoding. So the byte 0x87 is ambiguous, depending on if you
interpret it as codepage 1252 or UTF-8. How would a program know to use
1252 or UTF-8 to read the text file?

One solution might be to list all the UTF-8 byte sequences in the LHS of
a TECkit map. Since longer sequences are matched first, something like
0xE0 0xA5 0x87 would map to U+0947, 0x87 would map to U+090F DEVANAGARI
LETTER E

> I need to keep this simple for non-tech users to be able to use. The
> very proposal of converting and inputting everything in Unicode has
> taken over 4 years. These documents are working papers and books which
> will be on the web. As soon as we convert them to Unicode, they can be
> searched, indexed, analyzed, ...
>
What format are the papers and books in? If it is something like
Microsoft Word or LibreOffice Writer, we have tools such as Encoding
Converters at https://scripts.sil.org/EncCnvtrs that can read a Word
file, and then look at what font is used for the text, and can be
configured so that a TECkit map is only applied to text using the legacy
font. Encoding Converters also has a number of Devanagari maps that
might be useful to you.

-- 
Bobby de Vos
/bobby_devos@sil.org/

**Comment by kaanchan** [comment]
The organization uses Windows. MS Word automatically found Kokila as best APS-C-DV (legacy Devanagari font) substitute one day, and they indeed are very visually similar. I am developing the TECkit map on macOS which is what I have access to for the development.

Thanks for the link to Encoding Converters. It looks like it is a Windows only build, but it really does claim to provide the whole set of use cases we could want (clipboard-based conversion, full document conversion, transliteration, existing legacy Devanagari to Unicode font mappings, ...). Documents needing conversion are in MS Word format (.doc and .docx). Books are in InDesign format (.indd, but can be saved as XML .idml format). The ability to apply conversion to a specific legacy font is ideal.

For the example I had provided (with Unicode on top line and legacy encoded font on bottom line), I copied and pasted from TextEdit, a Unicode capable editor on macOS. 

Thanks to your example of the DEVANAGARI VOWEL SIGN E, I am clearer on how TECkit is processing the input file (for legacy to Unicode conversions) - essentially just a stream of bytes. And since UTF-8 stores a Unicode character as more than one byte, it's not a one-to-one mapping. Hence your suggestion to try decomposing and placing the actual byte value sequence on the left hand side is really clever and a practical workaround. 

I understand what I was seeing now in my first [test conversion](https://github.com/silnrsi/teckit/files/2626001/sample-legacy.txt), where each line started with a Unicode character. It was being mapped as three unknown mapping replacement characters in [the output](https://github.com/silnrsi/teckit/files/2626002/sample-unicode.txt)- one for each of the unmapped bytes. 

If you know an easy way to get the UTF-8 encoding for any given character, please let me know. I have [a table](https://github.com/silnrsi/teckit/files/2626034/Unicode-APS-maps.copy.xlsx) of all the ones of interest.

**Comment by DavidLRowe** [comment]
You might look at https://r12a.github.io/uniview/ . Select a block or enter a range to display a chart. Click on a character and it displays a lot of information, including the UTF-8 encoding.

**Comment by kaanchan** [comment]
That's a very comprehensive interface, thanks. I also came across the following which were useful:

- http://www.ltg.ed.ac.uk/~richard/utf-8.cgi - allows inputted Unicode representation to be interpreted a number of different ways (character, hex, decimal, ...) and accordingly displays the other representations
- https://mothereff.in/utf-8

**Comment by devosb** [comment]
In addition to Encoding Converters there is also an extension for LibreOffice which provides similar functionality at https://github.com/silnrsi/libreoffice-linguistic-tools Not sure if that will work on a macOS.

You need to be careful with using different platforms, such as Windows and macOS. In a legacy byte file, 0xE3 will be read as LATIN SMALL LETTER A WITH TILDE on Windows. On macOS, that same byte will be read as DOUBLE LOW-9 QUOTATION MARK. Well, that is if you have Western versions of Windows or macOS. If you have, let's say a Thai version then you will get (most likely) a Thai character for that byte.

I would guess that TextEdit is not storing data in memory in a mixed encoding, a Unicode encoding (such UTF-8, UTF-16LE would be used. So if you open a non-Unicode file with TextEdit, you will get U+201E DOUBLE LOW-9 QUOTATION MARK in the editor window.

Also, with a text file using a mixed Unicode and legacy encoding, you will need to know how the Unicode characters are stored (UTF-8, UTF-16LE, etc.) That will affect the bytes in the file.

On the Unicode side of the TECkit map, you can specify the Unicode character by name (with spaces converted to underscores) such as DEVANAGARI_VOWEL_SIGN E instead of U+090F.

When I copied your example of a mixed encoding from GitHub using Chrome I pasted the text into gedit (on Ubuntu) and saved the file. The file was UTF-8, so the LATIN SMALL LETTER A WITH TILDE was stored in the file as two bytes. A Unicode character such as U+0061 LATIN SMALL LETTER A will be stored in UTF-8 as one byte (0x61).
